### ISSUE TITLE
scalar_field_cell_level don't render in 3D

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/cc3d-player5#15]
If you assign a scalar_field_cell_level to cells, those values do not render in 3D window showing the field. Instead, the cells are rendered with whatever color is assigned to the cell. The field does render properly in 2D. In the attached image the upper left hand window is a scalar_field_cell_level in 3D that is colored wrong, and the right hand upper image is a 2D display of another scalar_field_cell_level the colors correctly.

![Untitled](https://user-images.githubusercontent.com/22944062/190502778-77010704-088b-49e4-ace2-d077a831d17f.png)

**Comment by jpsluka** [comment]
In addition, if the cell's scalar_field_cell_level is zero then the cell is not displayed at all in 3D.

**Comment by jpsluka** [comment]
It looks like the problem might be player is NOT treating field values as being different from cell types (or perhaps cell IDs).  It looks like any cell with field value between -1 and +0.999... is not displayed. Perhaps because Player is interpreting that as medium, which is not being displayed in 3D?

In the attached demo, note the mising cells with field values of -1 and 0.
[Test.zip](https://github.com/CompuCell3D/cc3d-player5/files/9579340/Test.zip)

**Comment by maciekswat** [comment]
This should be already fixed
