### ISSUE TITLE
Create movie crashes Player and problems with subsequent Player instances.

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/cc3d-player5#51]
Windows 11, Player 4.5.0 rev 2
If you use Player's settings window to create a movie, then Player crashes with the error
`INFO: Step 470 Flips 93/10000 Energy 66.9185 Cells 55 Inventory=55

INFO: Step 480 Flips 132/10000 Energy -60.0654 Cells 55 Inventory=55

Making movie inside ` C:\Users\jsluka\CC3DWorkspace\FPP_visualize_bug_cc3d_03_12_2024_16_58_14 `
Traceback (most recent call last):
  File "C:\CompuCell3D\Miniconda3\lib\site-packages\cc3d\player5\Configuration\ConfigurationDialog.py", line 204, in createMovieButtonClicked
    movieCount, moviePath = makeMovie(simulationPath, frameRate, quality, enableDrawingMCS)
  File "C:\CompuCell3D\Miniconda3\lib\site-packages\cc3d\core\GraphicsUtils\MovieCreator.py", line 74, in makeMovie
    subprocess.run([
  File "C:\CompuCell3D\Miniconda3\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\CompuCell3D\Miniconda3\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\CompuCell3D\Miniconda3\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
QThread: Destroyed while thread is still running
CLOSING LOCAL SOCKET
`

If you then relaunch Player, then Player's stop button crashes Player and gives the same error message as when generating a movie.

To fix Player, you have to delete both the project's and the global _settings.sqlite files. Or edit both _settings.sqlite files setting "AutomaticMovie" to zero.

A project that produces this bug is attached.

[FPP_visualize_bug.zip](https://github.com/CompuCell3D/cc3d-player5/files/14579640/FPP_visualize_bug.zip)

**Comment by fyffep** [comment]
I am not immediately able to reproduce this bug. @jpsluka do you still have a broken _settings.sqlite file that I can use?  
Regardless, I do see some space for guardrails. It was my mistake to allow Player to crash when the movie fails to create.

**Comment by jpsluka** [comment]
The zip file in the original post has the sqlite file.
